// A dependency-free QR encoder.
//
// WHY THIS EXISTS. The site is static and carries no external dependency of
// any kind (see CLAUDE.md): no npm package ships in the bundle, and nothing
// is fetched from a CDN. A QR library would be either of those, so the QR
// code on the event editor's dialog is drawn by the module below instead.
//
// SCOPE, ON PURPOSE. Byte mode only, error correction level M only, versions
// 1 through 10 only, with the version chosen automatically for whatever text
// is handed in. The payload is always a check-in URL of roughly 45
// characters, and version 3 already holds that; versions up to 10 are
// headroom for a longer origin, not an attempt at a general-purpose encoder.
// Alphanumeric and kanji modes, ECI, and versions above 10 are not
// implemented, because nothing in this product ever needs them.
//
// The algorithm follows ISO/IEC 18004 (byte-mode encoding, Reed-Solomon error
// correction over GF(256), the eight standard mask patterns scored by the
// four penalty rules, and the BCH-coded format and version information
// blocks). Every constant below (the per-version data/ECC split, the
// alignment pattern centres, the remainder-bit counts, the two BCH generator
// polynomials) is public specification data, not a judgement call.

// ---------------------------------------------------------------------------
// GF(256) arithmetic
// ---------------------------------------------------------------------------
// QR's Reed-Solomon codewords live in the field generated by the primitive
// polynomial x^8 + x^4 + x^3 + x^2 + 1 (0x11D), with generator element 2.
// Exp/log tables turn multiplication into addition, which is what makes the
// generator-polynomial and syndrome arithmetic below a table lookup rather
// than a polynomial reduction on every call.

const GF_EXP = new Uint8Array(512);
const GF_LOG = new Uint8Array(256);

(function buildGaloisTables() {
  let x = 1;
  for (let i = 0; i < 255; i += 1) {
    GF_EXP[i] = x;
    GF_LOG[x] = i;
    x <<= 1;
    if (x & 0x100) x ^= 0x11d;
  }
  for (let i = 255; i < 512; i += 1) GF_EXP[i] = GF_EXP[i - 255];
})();

function gfMul(a, b) {
  if (a === 0 || b === 0) return 0;
  return GF_EXP[GF_LOG[a] + GF_LOG[b]];
}

/**
 * Coefficients highest-degree-first, the same convention the QR generator
 * polynomial and Reed-Solomon division both use below.
 */
function polyMultiply(a, b) {
  const out = new Array(a.length + b.length - 1).fill(0);
  for (let i = 0; i < a.length; i += 1) {
    if (a[i] === 0) continue;
    for (let j = 0; j < b.length; j += 1) {
      out[i + j] ^= gfMul(a[i], b[j]);
    }
  }
  return out;
}

/** The generator polynomial for `degree` Reed-Solomon codewords: (x-1)(x-2)(x-4)... */
function generatorPolynomial(degree) {
  let g = [1];
  for (let i = 0; i < degree; i += 1) {
    g = polyMultiply(g, [1, GF_EXP[i]]);
  }
  return g;
}

/**
 * The `eccCount` Reed-Solomon parity codewords for one block: the remainder
 * of the data polynomial, shifted up by `eccCount`, divided by the generator
 * polynomial, computed by the same repeated-XOR long division every QR
 * encoder uses instead of a general polynomial-mod routine.
 */
function reedSolomonRemainder(dataCodewords, eccCount) {
  const generator = generatorPolynomial(eccCount);
  const remainder = new Uint8Array(dataCodewords.length + eccCount);
  remainder.set(dataCodewords);
  for (let i = 0; i < dataCodewords.length; i += 1) {
    const factor = remainder[i];
    if (factor === 0) continue;
    for (let j = 0; j < generator.length; j += 1) {
      remainder[i + j] ^= gfMul(generator[j], factor);
    }
  }
  return Array.from(remainder.slice(dataCodewords.length));
}

// ---------------------------------------------------------------------------
// Per-version tables, level M only (ISO/IEC 18004 Table 9 and Annex E)
// ---------------------------------------------------------------------------

/**
 * Index 0 unused, so a version number indexes directly.
 * [dataCodewords, eccCodewordsPerBlock, group1Blocks, group1Len, group2Blocks, group2Len]
 */
export const ECC_TABLE_M = [
  null,
  [16, 10, 1, 16, 0, 0],
  [28, 16, 1, 28, 0, 0],
  [44, 26, 1, 44, 0, 0],
  [64, 18, 2, 32, 0, 0],
  [86, 24, 2, 43, 0, 0],
  [108, 16, 4, 27, 0, 0],
  [124, 18, 4, 31, 0, 0],
  [154, 22, 2, 38, 2, 39],
  [182, 22, 3, 36, 2, 37],
  [216, 26, 4, 43, 1, 44],
];

// Trailing padding bits after the interleaved codewords, needed so the
// symbol's fixed module count divides evenly into whole codewords.
const REMAINDER_BITS = [null, 0, 7, 7, 7, 7, 7, 0, 0, 0, 0];

// Alignment pattern centre coordinates, combined pairwise (see placeAlignmentPatterns).
const ALIGNMENT_COORDS = [
  null,
  [],
  [6, 18],
  [6, 22],
  [6, 26],
  [6, 30],
  [6, 34],
  [6, 22, 38],
  [6, 24, 42],
  [6, 26, 46],
  [6, 28, 50],
];

const symbolSize = (version) => 17 + 4 * version;

// ---------------------------------------------------------------------------
// Bit stream: mode, character count, byte data, terminator, padding
// ---------------------------------------------------------------------------

class BitWriter {
  constructor() {
    this.bits = [];
  }
  push(value, length) {
    for (let i = length - 1; i >= 0; i -= 1) this.bits.push((value >>> i) & 1);
  }
  get length() {
    return this.bits.length;
  }
  toBytes() {
    const bytes = [];
    for (let i = 0; i < this.bits.length; i += 8) {
      let byte = 0;
      for (let b = 0; b < 8; b += 1) byte = (byte << 1) | (this.bits[i + b] ?? 0);
      bytes.push(byte);
    }
    return bytes;
  }
}

const MODE_BYTE = 0b0100;

/** 8 bits for versions 1-9, 16 for version 10 (byte mode; ISO 18004 Table 3). */
const charCountBits = (version) => (version <= 9 ? 8 : 16);

/**
 * The smallest version (1-10) whose level-M capacity holds this many payload
 * bytes in byte mode, or null when even version 10 cannot.
 */
function chooseVersion(byteLength) {
  for (let version = 1; version <= 10; version += 1) {
    const capacityBits = ECC_TABLE_M[version][0] * 8;
    const neededBits = 4 + charCountBits(version) + byteLength * 8;
    if (neededBits <= capacityBits) return version;
  }
  return null;
}

function buildCodewords(version, bytes) {
  const [dataCodewordCount] = ECC_TABLE_M[version];
  const writer = new BitWriter();
  writer.push(MODE_BYTE, 4);
  writer.push(bytes.length, charCountBits(version));
  for (const byte of bytes) writer.push(byte, 8);

  const capacityBits = dataCodewordCount * 8;
  const terminatorLength = Math.min(4, capacityBits - writer.length);
  if (terminatorLength > 0) writer.push(0, terminatorLength);
  while (writer.length % 8 !== 0) writer.push(0, 1);

  const dataCodewords = writer.toBytes();
  const padBytes = [0xec, 0x11];
  let padIndex = 0;
  while (dataCodewords.length < dataCodewordCount) {
    dataCodewords.push(padBytes[padIndex % 2]);
    padIndex += 1;
  }
  return dataCodewords;
}

/**
 * Data codewords split into their RS blocks, error-corrected, and
 * interleaved column-by-column the way ISO 18004 8.7.3 lays them into the
 * final stream: read one codeword from each block in turn, shorter blocks
 * simply running out first.
 */
function interleave(version, dataCodewords) {
  const [, eccPerBlock, g1Count, g1Len, g2Count, g2Len] = ECC_TABLE_M[version];

  const blocks = [];
  let at = 0;
  for (let i = 0; i < g1Count; i += 1) {
    blocks.push(dataCodewords.slice(at, at + g1Len));
    at += g1Len;
  }
  for (let i = 0; i < g2Count; i += 1) {
    blocks.push(dataCodewords.slice(at, at + g2Len));
    at += g2Len;
  }

  const eccBlocks = blocks.map((block) => reedSolomonRemainder(block, eccPerBlock));

  const out = [];
  const maxDataLen = Math.max(g1Len, g2Len || 0);
  for (let i = 0; i < maxDataLen; i += 1) {
    for (const block of blocks) if (i < block.length) out.push(block[i]);
  }
  for (let i = 0; i < eccPerBlock; i += 1) {
    for (const block of eccBlocks) out.push(block[i]);
  }
  return out;
}

// ---------------------------------------------------------------------------
// BCH-coded format and version information
// ---------------------------------------------------------------------------

/** Degree of a bit pattern: the position of its highest set bit, or -1 for 0. */
function bchDegree(value) {
  let digit = 0;
  let v = value;
  while (v !== 0) {
    v >>>= 1;
    digit += 1;
  }
  return digit;
}

// Format information: BCH(15,5), generator 0x537, XORed with the fixed mask
// 0x5412 so an all-format-zero symbol never encodes as all-zero data.
const FORMAT_GENERATOR = 0x537;
const FORMAT_MASK = 0x5412;

// ECC level indicator bits used inside format information (ISO 18004 Table
// 25). Only 'M' is ever produced here; the others are listed for clarity.
const ECC_INDICATOR = { L: 0b01, M: 0b00, Q: 0b11, H: 0b10 };

/** The 15-bit format information string for level M and one of the 8 masks. */
export function formatBits(maskPattern) {
  const data = (ECC_INDICATOR.M << 3) | maskPattern; // 5 bits
  let remainder = data << 10;
  const generatorDegree = bchDegree(FORMAT_GENERATOR);
  while (bchDegree(remainder) >= generatorDegree) {
    remainder ^= FORMAT_GENERATOR << (bchDegree(remainder) - generatorDegree);
  }
  return ((data << 10) | remainder) ^ FORMAT_MASK;
}

// Version information: BCH(18,6), generator 0x1F25, no mask. Only used for
// versions 7 and up; versions 1-6 carry no version information block.
const VERSION_GENERATOR = 0x1f25;

function versionBits(version) {
  let remainder = version << 12;
  const generatorDegree = bchDegree(VERSION_GENERATOR);
  while (bchDegree(remainder) >= generatorDegree) {
    remainder ^= VERSION_GENERATOR << (bchDegree(remainder) - generatorDegree);
  }
  return (version << 12) | remainder;
}

// ---------------------------------------------------------------------------
// The eight mask patterns (ISO 18004 Table 10)
// ---------------------------------------------------------------------------

const MASK_FUNCTIONS = [
  (r, c) => (r + c) % 2 === 0,
  (r) => r % 2 === 0,
  (r, c) => c % 3 === 0,
  (r, c) => (r + c) % 3 === 0,
  (r, c) => (Math.floor(r / 2) + Math.floor(c / 3)) % 2 === 0,
  (r, c) => ((r * c) % 2) + ((r * c) % 3) === 0,
  (r, c) => (((r * c) % 2) + ((r * c) % 3)) % 2 === 0,
  (r, c) => (((r + c) % 2) + ((r * c) % 3)) % 2 === 0,
];

// ---------------------------------------------------------------------------
// The matrix: function patterns, data placement, masking, scoring
// ---------------------------------------------------------------------------

function makeGrid(size, fill) {
  return Array.from({ length: size }, () => new Array(size).fill(fill));
}

function drawFinderPattern(modules, isFunction, top, left, size) {
  for (let dr = -1; dr <= 7; dr += 1) {
    const r = top + dr;
    if (r < 0 || r >= size) continue;
    for (let dc = -1; dc <= 7; dc += 1) {
      const c = left + dc;
      if (c < 0 || c >= size) continue;
      isFunction[r][c] = true;
      const inSquare = dr >= 0 && dr <= 6 && dc >= 0 && dc <= 6;
      const onRing = dr === 0 || dr === 6 || dc === 0 || dc === 6;
      const inCore = dr >= 2 && dr <= 4 && dc >= 2 && dc <= 4;
      modules[r][c] = inSquare && (onRing || inCore);
    }
  }
}

function drawAlignmentPattern(modules, isFunction, row, col) {
  for (let dr = -2; dr <= 2; dr += 1) {
    for (let dc = -2; dc <= 2; dc += 1) {
      const r = row + dr;
      const c = col + dc;
      isFunction[r][c] = true;
      modules[r][c] = Math.max(Math.abs(dr), Math.abs(dc)) !== 1;
    }
  }
}

/**
 * Every pairwise combination of the version's alignment coordinates, except
 * the three that would fall on a finder pattern (top-left, top-right,
 * bottom-left). Drawn after the finder patterns and before the timing
 * pattern, so a centre that lands on the timing row or column (real QR
 * symbols have several) correctly overrides it rather than the other way
 * round.
 */
function placeAlignmentPatterns(modules, isFunction, version) {
  const coords = ALIGNMENT_COORDS[version];
  if (!coords.length) return;
  const first = coords[0];
  const last = coords[coords.length - 1];
  for (const row of coords) {
    for (const col of coords) {
      const isFinderCorner =
        (row === first && col === first) ||
        (row === first && col === last) ||
        (row === last && col === first);
      if (isFinderCorner) continue;
      drawAlignmentPattern(modules, isFunction, row, col);
    }
  }
}

function placeTimingPatterns(modules, isFunction, size) {
  for (let i = 8; i < size - 8; i += 1) {
    if (!isFunction[6][i]) {
      isFunction[6][i] = true;
      modules[6][i] = i % 2 === 0;
    }
    if (!isFunction[i][6]) {
      isFunction[i][6] = true;
      modules[i][6] = i % 2 === 0;
    }
  }
}

/**
 * The 15 module coordinates of each format-information copy, in bit order
 * 0..14. Copy 1 hugs the top-left finder, split across its two arms; copy 2
 * runs along the bottom of the top-right finder and the right of the
 * bottom-left finder, which is what survives if one copy is damaged.
 *
 * THIS IS THE ONLY PLACE THESE COORDINATES ARE COMPUTED. Reserving the area
 * (so placeData skips it) and writing the real bits into it used to be two
 * separately hand-written loops that quietly disagreed: the reservation loop
 * claimed a naive 9-cell square on each arm, two cells wider than either
 * copy actually is, which stole two modules out of the data region
 * ((8, size-9) and (size-9, 8), never written by either copy). placeData had
 * nowhere left to put the last two bits of the interleaved codeword stream,
 * so they were silently never placed at all, and an independent decoder
 * reading those two coordinates as the ordinary data modules they are in a
 * real symbol read the wrong thing there and failed the whole block. Every
 * version was affected, because the bug was in the always-present format
 * area, not in anything version-specific. Deriving the reservation from the
 * exact same list the write uses makes the two impossible to drift apart
 * again.
 */
function formatInfoCoords(size) {
  const copy1 = [];
  for (let i = 0; i <= 5; i += 1) copy1.push([i, 8]);
  copy1.push([7, 8], [8, 8], [8, 7]);
  for (let i = 9; i <= 14; i += 1) copy1.push([8, 14 - i]);

  const copy2 = [];
  for (let i = 0; i <= 7; i += 1) copy2.push([8, size - 1 - i]);
  for (let i = 8; i <= 14; i += 1) copy2.push([size - 15 + i, 8]);

  return [...copy1, ...copy2];
}

/** Reserves both format-information strips, filled in after masking. */
function reserveFormatArea(isFunction, size) {
  for (const [r, c] of formatInfoCoords(size)) isFunction[r][c] = true;
}

function writeFormatBits(modules, maskPattern) {
  const size = modules.length;
  const bits = formatBits(maskPattern);
  const coords = formatInfoCoords(size);
  coords.forEach(([r, c], i) => {
    modules[r][c] = Boolean((bits >> (i % 15)) & 1);
  });

  // The one module that is always dark, regardless of mask or data.
  modules[size - 8][8] = true;
}

function reserveVersionArea(isFunction, size, version) {
  if (version < 7) return;
  for (let r = 0; r < 6; r += 1) {
    for (let c = 0; c < 3; c += 1) {
      isFunction[r][size - 11 + c] = true;
      isFunction[size - 11 + c][r] = true;
    }
  }
}

function writeVersionBits(modules, version) {
  if (version < 7) return;
  const size = modules.length;
  const bits = versionBits(version);
  for (let i = 0; i < 18; i += 1) {
    const on = Boolean((bits >> i) & 1);
    const row = Math.floor(i / 3);
    const col = i % 3;
    modules[row][size - 11 + col] = on;
    modules[size - 11 + col][row] = on;
  }
}

/**
 * Places the interleaved codeword bits into every module that is not a
 * function pattern, in the standard zigzag: two-column strips moving
 * bottom-to-top then top-to-bottom, right-to-left, always skipping column 6
 * (the vertical timing pattern) as if it were not there.
 *
 * `col` is decremented in place, not read into a second variable, because
 * the skip at column 6 has to shift every later pair by one: the pairs
 * after it are (5,4), (3,2), (1,0), not (5,4), (4,3), (2,1). A loop that
 * computed the post-skip column separately from the one driving `-= 2`
 * would visit column 4 twice and column 0 never, which is corrupt in a way
 * that a version with only one Reed-Solomon block (version 1-3) is too
 * small to expose but every larger version is.
 */
function placeData(modules, isFunction, size, codewordBits) {
  let bitIndex = 0;
  let row = size - 1;
  let rowStep = -1;
  for (let col = size - 1; col > 0; col -= 2) {
    if (col === 6) col -= 1;
    for (;;) {
      for (let c = 0; c < 2; c += 1) {
        const cc = col - c;
        if (!isFunction[row][cc]) {
          modules[row][cc] = bitIndex < codewordBits.length && codewordBits[bitIndex] === 1;
          bitIndex += 1;
        }
      }
      row += rowStep;
      if (row < 0 || row >= size) {
        row -= rowStep;
        rowStep = -rowStep;
        break;
      }
    }
  }
  return bitIndex;
}

function codewordsToBits(codewords, remainderBits) {
  const bits = [];
  for (const byte of codewords) for (let i = 7; i >= 0; i -= 1) bits.push((byte >> i) & 1);
  for (let i = 0; i < remainderBits; i += 1) bits.push(0);
  return bits;
}

function applyMask(modules, isFunction, size, maskFn) {
  const out = makeGrid(size, false);
  for (let r = 0; r < size; r += 1) {
    for (let c = 0; c < size; c += 1) {
      out[r][c] = isFunction[r][c] ? modules[r][c] : modules[r][c] !== maskFn(r, c);
    }
  }
  return out;
}

// ---------------------------------------------------------------------------
// Penalty scoring (ISO 18004 Annex A: the four rules that pick a mask)
// ---------------------------------------------------------------------------

function penaltyRunsIn(line) {
  let score = 0;
  let runLength = 1;
  for (let i = 1; i <= line.length; i += 1) {
    if (i < line.length && line[i] === line[i - 1]) {
      runLength += 1;
      continue;
    }
    if (runLength >= 5) score += 3 + (runLength - 5);
    runLength = 1;
  }
  return score;
}

function penaltyRule1(grid, size) {
  let score = 0;
  for (let r = 0; r < size; r += 1) score += penaltyRunsIn(grid[r]);
  for (let c = 0; c < size; c += 1) score += penaltyRunsIn(grid.map((row) => row[c]));
  return score;
}

function penaltyRule2(grid, size) {
  let score = 0;
  for (let r = 0; r < size - 1; r += 1) {
    for (let c = 0; c < size - 1; c += 1) {
      const v = grid[r][c];
      if (v === grid[r][c + 1] && v === grid[r + 1][c] && v === grid[r + 1][c + 1]) score += 3;
    }
  }
  return score;
}

// dark-light-dark-dark-dark-light-dark, with four light modules on one side.
const FINDER_LIKE = [true, false, true, true, true, false, true];

function hasFinderLikePattern(line, at) {
  for (let i = 0; i < FINDER_LIKE.length; i += 1) {
    if (line[at + i] !== FINDER_LIKE[i]) return false;
  }
  return true;
}

function penaltyRule3Line(line) {
  let score = 0;
  for (let i = 0; i + 7 <= line.length; i += 1) {
    if (!hasFinderLikePattern(line, i)) continue;
    const lightBefore = line.slice(Math.max(0, i - 4), i).every((v) => v === false);
    const lightAfter = line.slice(i + 7, i + 11).every((v) => v === false);
    const fullBefore = i - 4 >= 0 && lightBefore;
    const fullAfter = i + 11 <= line.length && lightAfter;
    if (fullBefore || fullAfter) score += 40;
  }
  return score;
}

function penaltyRule3(grid, size) {
  let score = 0;
  for (let r = 0; r < size; r += 1) score += penaltyRule3Line(grid[r]);
  for (let c = 0; c < size; c += 1) score += penaltyRule3Line(grid.map((row) => row[c]));
  return score;
}

function penaltyRule4(grid, size) {
  let dark = 0;
  for (let r = 0; r < size; r += 1) for (let c = 0; c < size; c += 1) if (grid[r][c]) dark += 1;
  const percent = (dark * 100) / (size * size);
  const deviation = Math.floor(Math.abs(percent - 50) / 5) * 10;
  return deviation;
}

function totalPenalty(grid, size) {
  return (
    penaltyRule1(grid, size) + penaltyRule2(grid, size) + penaltyRule3(grid, size) + penaltyRule4(grid, size)
  );
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * @param {string} text ASCII/Latin-1 text (a URL, here). Encoded byte for
 *   byte: nothing in this product's payload needs multi-byte characters.
 * @returns {{
 *   version: number, size: number, mask: number, eccLevel: 'M',
 *   modules: boolean[][], isFunction: boolean[][], codewords: number[]
 * }}
 */
export function encodeQR(text) {
  const bytes = Array.from(text, (ch) => ch.charCodeAt(0) & 0xff);
  const version = chooseVersion(bytes.length);
  if (!version) throw new Error('Text is too long for a version 1-10 QR code at error correction level M.');

  const dataCodewords = buildCodewords(version, bytes);
  const codewords = interleave(version, dataCodewords);
  const codewordBits = codewordsToBits(codewords, REMAINDER_BITS[version]);

  const size = symbolSize(version);
  const modules = makeGrid(size, false);
  const isFunction = makeGrid(size, false);

  drawFinderPattern(modules, isFunction, 0, 0, size);
  drawFinderPattern(modules, isFunction, size - 7, 0, size);
  drawFinderPattern(modules, isFunction, 0, size - 7, size);
  placeAlignmentPatterns(modules, isFunction, version);
  placeTimingPatterns(modules, isFunction, size);
  reserveFormatArea(isFunction, size);
  reserveVersionArea(isFunction, size, version);
  isFunction[size - 8][8] = true; // the fixed dark module

  placeData(modules, isFunction, size, codewordBits);

  let bestMask = 0;
  let bestScore = Infinity;
  let bestGrid = null;
  for (let mask = 0; mask < 8; mask += 1) {
    const candidate = applyMask(modules, isFunction, size, MASK_FUNCTIONS[mask]);
    const score = totalPenalty(candidate, size);
    if (score < bestScore) {
      bestScore = score;
      bestMask = mask;
      bestGrid = candidate;
    }
  }

  writeFormatBits(bestGrid, bestMask);
  writeVersionBits(bestGrid, version);

  return { version, size, mask: bestMask, eccLevel: 'M', modules: bestGrid, isFunction, codewords };
}

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

// THE QUIET ZONE IS FOUR MODULES, NOT TWO. ISO/IEC 18004 requires a clear
// margin of four modules on every side of a QR symbol (two is the Micro QR
// figure, and is the easy mistake). A narrower margin still decodes from a
// clean raster, which is exactly why getting this wrong survives testing: it
// fails later, on a printed sheet where something is placed near the code, on
// a coloured background, or at the angle somebody actually holds a phone at.
const QUIET_ZONE = 4;

const SVG_NS = 'http://www.w3.org/2000/svg';

/**
 * The QR code as an inline <svg>, built with createElementNS the way
 * ui.js's chevron() is: no innerHTML anywhere in this codebase, and an SVG
 * assembled with the plain HTML createElement lands in the wrong namespace
 * and renders as nothing.
 *
 * One <path> carries every dark module, rather than one <rect> per module:
 * a version 10 code is 57x57 modules, and a wall of three thousand rect
 * elements is not something this dialog needs to pay for.
 */
export function qrToSvgElement(qr, { pixelSize = 240, margin = QUIET_ZONE } = {}) {
  const { size, modules } = qr;
  const total = size + margin * 2;

  const svg = document.createElementNS(SVG_NS, 'svg');
  svg.setAttribute('viewBox', `0 0 ${total} ${total}`);
  svg.setAttribute('width', String(pixelSize));
  svg.setAttribute('height', String(pixelSize));
  svg.setAttribute('role', 'img');
  svg.setAttribute('aria-label', 'Check-in QR code');
  svg.setAttribute('shape-rendering', 'crispEdges');

  const background = document.createElementNS(SVG_NS, 'rect');
  background.setAttribute('x', '0');
  background.setAttribute('y', '0');
  background.setAttribute('width', String(total));
  background.setAttribute('height', String(total));
  background.setAttribute('fill', '#fff');
  svg.append(background);

  let d = '';
  for (let r = 0; r < size; r += 1) {
    for (let c = 0; c < size; c += 1) {
      if (!modules[r][c]) continue;
      const x = c + margin;
      const y = r + margin;
      d += `M${x},${y}h1v1h-1z`;
    }
  }
  const path = document.createElementNS(SVG_NS, 'path');
  path.setAttribute('d', d);
  path.setAttribute('fill', '#000');
  svg.append(path);

  return svg;
}

/** The same code drawn onto a <canvas>, for the PNG download. */
export function qrDrawToCanvas(qr, canvas, { pixelSize = 512, margin = QUIET_ZONE } = {}) {
  const { size, modules } = qr;
  const total = size + margin * 2;
  const scale = Math.max(1, Math.floor(pixelSize / total));
  const drawn = total * scale;

  canvas.width = drawn;
  canvas.height = drawn;
  const ctx = canvas.getContext('2d');
  ctx.fillStyle = '#fff';
  ctx.fillRect(0, 0, drawn, drawn);
  ctx.fillStyle = '#000';
  for (let r = 0; r < size; r += 1) {
    for (let c = 0; c < size; c += 1) {
      if (!modules[r][c]) continue;
      ctx.fillRect((c + margin) * scale, (r + margin) * scale, scale, scale);
    }
  }
  return canvas;
}
